spring.application.name=simulador-emprestimo


spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

taxas-juros.ate-25=0.05
taxas-juros.de-26-a-40=0.03
taxas-juros.de-41-a-60=0.02
taxas-juros.acima-60=0.04

envia-email=false



